from pathlib import Path
p=Path('/mnt/data/phase6_work/server/app/main.py')
s=p.read_text()
s=s.replace('import uuid\nfrom typing import Dict, Set', 'import uuid\nimport sqlite3\nfrom pathlib import Path\nfrom collections import defaultdict, deque\nfrom typing import Dict, Set\nfrom fastapi import Request')
s=s.replace('app = FastAPI(title="Raksha Video Signaling", version="0.1.0")\nrooms:', '''APP_VERSION = os.getenv("RAKSHA_VERSION", "0.1.0")\nAUTH_TOKEN = os.getenv("RAKSHA_API_TOKEN", "")\nDB_PATH = Path(os.getenv("RAKSHA_DB_PATH", "./data/raksha.db"))\nDB_PATH.parent.mkdir(parents=True, exist_ok=True)\n\napp = FastAPI(title="Raksha Video", version=APP_VERSION)\n\ndef db_init():\n    with sqlite3.connect(DB_PATH) as db:\n        db.executescript("""\n        CREATE TABLE IF NOT EXISTS trusted_contacts (id TEXT PRIMARY KEY, payload TEXT NOT NULL);\n        CREATE TABLE IF NOT EXISTS safety_actions (idempotency_key TEXT PRIMARY KEY, payload TEXT NOT NULL);\n        CREATE TABLE IF NOT EXISTS evidence (id TEXT PRIMARY KEY, session_id TEXT NOT NULL, payload TEXT NOT NULL);\n        CREATE INDEX IF NOT EXISTS idx_evidence_session ON evidence(session_id);\n        """)\n\ndef auth_ok(value: str | None) -> bool:\n    return bool(AUTH_TOKEN) and value == f"Bearer {AUTH_TOKEN}"\n\ndef require_auth(value: str | None):\n    if not AUTH_TOKEN:\n        raise HTTPException(503, "Authentication is not configured")\n    if not auth_ok(value):\n        raise HTTPException(401, "Unauthorized")\n\nrate_hits = defaultdict(deque)\nRATE_LIMIT = int(os.getenv("RAKSHA_RATE_LIMIT", "120"))\nRATE_WINDOW = 60\n\n@app.middleware("http")\nasync def rate_limit(request: Request, call_next):\n    if request.url.path in {"/health", "/ready", "/docs", "/openapi.json", "/redoc"}:\n        return await call_next(request)\n    host = request.client.host if request.client else "unknown"\n    now = time.monotonic()\n    q = rate_hits[host]\n    while q and now - q[0] > RATE_WINDOW:\n        q.popleft()\n    if len(q) >= RATE_LIMIT:\n        return JSONResponse(status_code=429, content={"error":"RATE_LIMITED","message":"Too many requests"})\n    q.append(now)\n    return await call_next(request)\n\n@app.on_event("startup")\nasync def startup():\n    db_init()\n\nrooms:''')
s=s.replace('from fastapi import FastAPI, WebSocket, WebSocketDisconnect, Header, HTTPException', 'from fastapi import FastAPI, WebSocket, WebSocketDisconnect, Header, HTTPException\nfrom fastapi.responses import JSONResponse')
s=s.replace('DEV_TOKEN = os.getenv("DEV_TOKEN", "dev-token")', '')
s=s.replace('    return {"status": "ok", "service": "raksha-video-signaling"}', '    return {"status": "ok", "service": "raksha-video", "version": APP_VERSION, "timestamp": int(time.time()*1000)}\n\n@app.get("/ready")\nasync def ready():\n    if not AUTH_TOKEN:\n        return JSONResponse(status_code=503, content={"status":"not_ready","reason":"authentication_not_configured"})\n    try:\n        with sqlite3.connect(DB_PATH) as db: db.execute("SELECT 1")\n    except Exception:\n        return JSONResponse(status_code=503, content={"status":"not_ready","reason":"database_unavailable"})\n    return {"status":"ready","version":APP_VERSION}')
s=s.replace('    if authorization != f"Bearer {DEV_TOKEN}":', '    require_auth(authorization)')
s=s.replace('    return {"ice_servers": servers}', '    return {"ice_servers": servers}')
# websocket auth and all remaining direct references
s=s.replace('    if authorization != f"Bearer {DEV_TOKEN}":', '    if not auth_ok(authorization):')
s=s.replace('    if authorization != f"Bearer {DEV_TOKEN}" or session_id not in protection_sessions:', '    if not auth_ok(authorization) or session_id not in protection_sessions:')
# public websocket URL construction
s=s.replace('    return {"session_id": session_id, "call_id": req.call_id, "websocket_url": f"ws://127.0.0.1:8000/api/ws/sessions/{session_id}", "expires_at": None}', '    public_ws = os.getenv("RAKSHA_PUBLIC_WS_BASE", "").rstrip("/")\n    websocket_url = f"{public_ws}/api/ws/sessions/{session_id}" if public_ws else f"/api/ws/sessions/{session_id}"\n    return {"session_id": session_id, "call_id": req.call_id, "websocket_url": websocket_url, "expires_at": None}')
# persistence load helpers inserted after dicts
needle='trusted_contacts: Dict[str, dict] = {}\nsafety_actions: Dict[str, dict] = {}\nsession_evidence: Dict[str, list[dict]] = {}\n'
replacement='''trusted_contacts: Dict[str, dict] = {}\nsafety_actions: Dict[str, dict] = {}\nsession_evidence: Dict[str, list[dict]] = {}\n\ndef load_persistent_state():\n    with sqlite3.connect(DB_PATH) as db:\n        for cid, payload in db.execute("SELECT id, payload FROM trusted_contacts"):\n            trusted_contacts[cid] = json.loads(payload)\n        for key, payload in db.execute("SELECT idempotency_key, payload FROM safety_actions"):\n            safety_actions[key] = json.loads(payload)\n        for eid, sid, payload in db.execute("SELECT id, session_id, payload FROM evidence"):\n            session_evidence.setdefault(sid, []).append(json.loads(payload))\n\ndef persist_contact(contact):\n    with sqlite3.connect(DB_PATH) as db:\n        db.execute("INSERT OR REPLACE INTO trusted_contacts(id,payload) VALUES(?,?)", (contact["id"], json.dumps(contact)))\n\ndef delete_contact(contact_id):\n    with sqlite3.connect(DB_PATH) as db: db.execute("DELETE FROM trusted_contacts WHERE id=?", (contact_id,))\n\ndef persist_action(key, result):\n    with sqlite3.connect(DB_PATH) as db: db.execute("INSERT OR REPLACE INTO safety_actions(idempotency_key,payload) VALUES(?,?)", (key, json.dumps(result)))\n\ndef persist_evidence(session_id, event):\n    with sqlite3.connect(DB_PATH) as db: db.execute("INSERT OR REPLACE INTO evidence(id,session_id,payload) VALUES(?,?,?)", (event["id"], session_id, json.dumps(event)))\n\nload_persistent_state()\n'''
s=s.replace(needle,replacement)
# persistence operations
s=s.replace('    trusted_contacts[cid] = contact\n    return contact', '    trusted_contacts[cid] = contact\n    persist_contact(contact)\n    return contact')
s=s.replace('    trusted_contacts[contact_id].update({k:v for k,v in payload.items() if k in allowed})\n    return trusted_contacts[contact_id]', '    trusted_contacts[contact_id].update({k:v for k,v in payload.items() if k in allowed})\n    persist_contact(trusted_contacts[contact_id])\n    return trusted_contacts[contact_id]')
s=s.replace('    if trusted_contacts.pop(contact_id, None) is None: raise HTTPException(404, "Contact not found")\n    return {"deleted": True}', '    if trusted_contacts.pop(contact_id, None) is None: raise HTTPException(404, "Contact not found")\n    delete_contact(contact_id)\n    return {"deleted": True}')
s=s.replace('    safety_actions[key] = result\n    session_evidence.setdefault(session_id, []).append({"id": action_id, "call_id": session["call_id"], "type": "SAFETY_ACTION", "timestamp": result["timestamp"], "description": req.action, "metadata": {"status":"ACCEPTED"}})', '    safety_actions[key] = result\n    persist_action(key, result)\n    evidence_event = {"id": action_id, "call_id": session["call_id"], "type": "SAFETY_ACTION", "timestamp": result["timestamp"], "description": req.action, "metadata": {"status":"ACCEPTED"}}\n    session_evidence.setdefault(session_id, []).append(evidence_event)\n    persist_evidence(session_id, evidence_event)')
# validation and max lengths
s=s.replace('    name = str(payload.get("displayName", "")).strip()\n    if not name:', '    name = str(payload.get("displayName", "")).strip()[:120]\n    if not name:')
s=s.replace('    text = str(payload.get("text", "")).strip()\n    if not text:', '    text = str(payload.get("text", "")).strip()[:4000]\n    if not text:')
s=s.replace('    if batch.session_id != session_id or batch.call_id != session["call_id"]:', '    if len(batch.signals) > 64: raise HTTPException(413, "Too many signals")\n    if batch.session_id != session_id or batch.call_id != session["call_id"]:')
# call room max 2 participants
s=s.replace('                room = requested\n                rooms.setdefault(room, set()).add(ws)', '                room = requested\n                if len(rooms.get(room, set())) >= 2:\n                    await ws.send_json({"version":1,"type":"error","request_id":str(uuid.uuid4()),"timestamp":int(time.time()*1000),"payload":{"message":"Call is full"}})\n                    continue\n                rooms.setdefault(room, set()).add(ws)')
p.write_text(s)
