import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {motion,AnimatePresence} from 'framer-motion';
import {Activity,AlertTriangle,Check,Download,FileText,Lock,Mic,Phone,Radio,ShieldCheck,Users,Video,Wifi,X,PauseCircle,ExternalLink} from 'lucide-react';
import './styles.css';

const API=import.meta.env.VITE_API_BASE||'';
async function req(path:string,opts:any={},token?:string){
 const r=await fetch(API+path,{...opts,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});
 if(!r.ok) throw new Error(await r.text()); return r.json();
}
function pcmToB64(buf:ArrayBuffer){let b='';const bytes=new Uint8Array(buf);for(let i=0;i<bytes.length;i++)b+=String.fromCharCode(bytes[i]);return btoa(b)}

function App(){
 const [token,setToken]=useState(localStorage.getItem('raksha_token')||'');
 const [authMode,setAuthMode]=useState<'login'|'register'>('login');
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState('');
 const [session,setSession]=useState<any>(null); const [risk,setRisk]=useState<any>({risk_level:'LOW',fused_score:0,conversation_score:0,visual_score:0,liveness_score:0,reasons:['Waiting for permitted conversation input.'],stage:'CONTACT'});
 const [transcript,setTranscript]=useState(''); const [ai,setAi]=useState<any>(null); const [aiStatus,setAiStatus]=useState('offline');
 const [mic,setMic]=useState(false); const [camera,setCamera]=useState(false); const [warning,setWarning]=useState(false); const [evidence,setEvidence]=useState<any>(null); const [toast,setToast]=useState('');
 const [contact,setContact]=useState<any>(null); const [stats,setStats]=useState<any>({});
 const ws=useRef<WebSocket|null>(null); const stream=useRef<MediaStream|null>(null); const audioCtx=useRef<AudioContext|null>(null); const worklet=useRef<AudioWorkletNode|null>(null); const source=useRef<MediaStreamAudioSourceNode|null>(null); const video=useRef<HTMLVideoElement>(null); const canvas=useRef<HTMLCanvasElement>(null); const frameTimer=useRef<any>(null); const recognition=useRef<any>(null);
 useEffect(()=>{if(token){loadStats();loadContact()}},[token]);
 useEffect(()=>()=>stopAll(),[]);
 function notify(x:string){setToast(x);setTimeout(()=>setToast(''),3200)}
 async function loadStats(){try{setStats(await req('/api/stats',{},token))}catch{logout()}}
 async function loadContact(){try{const x=await req('/api/contacts',{},token);setContact(x[0]||null)}catch{}}
 function logout(){stopAll();localStorage.removeItem('raksha_token');setToken('');setSession(null);setEmail('');setPassword('')}
 async function auth(){try{const path=authMode==='login'?'/api/auth/login':'/api/auth/register';const body=authMode==='login'?{email,password}:{email,password,name};const r=await req(path,{method:'POST',body:JSON.stringify(body)});localStorage.setItem('raksha_token',r.access_token);setToken(r.access_token);notify('Secure session unlocked')}catch(e:any){notify('Authentication failed: check credentials')}}
 async function start(){if(session)return session;const s=await req('/api/sessions',{method:'POST',body:JSON.stringify({source:'consented-live-microphone'})},token);setSession(s);connect(s.id);notify('Protection session started');return s}
 function connect(id:number){const proto=location.protocol==='https:'?'wss':'ws';const base=location.host;const socket=new WebSocket(`${proto}://${base}/api/ws/sessions/${id}`);ws.current=socket;socket.onmessage=e=>{const d=JSON.parse(e.data);if(d.type==='ai_status'){setAiStatus(d.status)}if(d.type==='transcript'){setTranscript(t=>(t+' '+d.text).trim())}if(d.type==='risk_update'){setRisk(d);if(d.risk_level==='HIGH')setWarning(true)}if(d.type==='ai_analysis'){setAi(d.analysis);if(d.risk_update){setRisk(d.risk_update);if(d.risk_update.risk_level==='HIGH')setWarning(true)}}};socket.onclose=()=>setAiStatus('offline')}
 async function startMic(){
   await start();
   if(mic){stopMic();return}
   try{
    const s=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:true}});
    stream.current=s;
    if(audioCtx.current) await audioCtx.current.close();
    const ctx=new AudioContext(); audioCtx.current=ctx;
    await ctx.audioWorklet.addModule('/pcm-processor.js');
    const src=ctx.createMediaStreamSource(s); const node=new AudioWorkletNode(ctx,'raksha-pcm-processor');
    node.port.onmessage=e=>{if(ws.current?.readyState===1)ws.current.send(JSON.stringify({type:'audio_pcm16',data:pcmToB64(e.data)}))};
    src.connect(node); const mute=ctx.createGain();mute.gain.value=0;node.connect(mute);mute.connect(ctx.destination);
    source.current=src;worklet.current=node;setMic(true);notify('Live microphone → Gemini Live connected');
   }catch{ // real fallback: browser speech recognition sends actual transcript text, no synthetic data
    const C:any=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;
    if(!C){notify('Microphone unavailable. Grant permission or use a supported browser.');return}
    const r=new C();recognition.current=r;r.continuous=true;r.interimResults=false;r.lang='en-IN';r.onresult=(e:any)=>{for(let i=e.resultIndex;i<e.results.length;i++){const text=e.results[i][0].transcript;if(text&&ws.current?.readyState===1)ws.current.send(JSON.stringify({type:'text',text}))}};r.onerror=()=>setMic(false);r.onend=()=>{if(mic)try{r.start()}catch{}};r.start();setMic(true);notify('Live speech recognition fallback active')
   }
 }
 function stopMic(){recognition.current?.stop();worklet.current?.disconnect();source.current?.disconnect();audioCtx.current?.close();stream.current?.getTracks().filter(t=>t.kind==='audio').forEach(t=>t.stop());setMic(false)}
 async function startCamera(){await start();if(camera){stopCamera();return}try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});stream.current=s;if(video.current){video.current.srcObject=s;await video.current.play()}setCamera(true);frameTimer.current=setInterval(()=>{if(!canvas.current||!video.current||ws.current?.readyState!==1)return;const c=canvas.current;c.width=320;c.height=240;const g=c.getContext('2d');if(!g)return;g.drawImage(video.current,0,0,320,240);c.toBlob(b=>{if(!b)return;b.arrayBuffer().then(a=>ws.current?.send(JSON.stringify({type:'video_jpeg',data:btoa(String.fromCharCode(...new Uint8Array(a)))})))},'image/jpeg',.55)},1200);notify('Consent-based camera frames sent for supporting visual analysis')}catch{notify('Camera permission was not granted')}}
 function stopCamera(){if(frameTimer.current)clearInterval(frameTimer.current);stream.current?.getTracks().filter(t=>t.kind==='video').forEach(t=>t.stop());setCamera(false)}
 function stopAll(){stopMic();stopCamera();ws.current?.close()}
 async function makeEvidence(){if(!session)return;try{const r=await req(`/api/sessions/${session.id}/evidence`,{method:'POST'},token);setEvidence(r.report);notify('Evidence chain generated and verified')}catch{notify('Evidence generation failed')}}
 async function alertContact(){if(!session)return;try{const r=await req(`/api/sessions/${session.id}/trusted-alert`,{method:'POST'},token);notify(r.status==='sent'?'Trusted-contact SMS sent':'SMS not sent: provider is not configured');}catch{notify('Trusted-contact alert failed')}}
 if(!token)return <Auth mode={authMode} setMode={setAuthMode} email={email} setEmail={setEmail} password={password} setPassword={setPassword} name={name} setName={setName} onSubmit={auth}/>;
 const high=risk.risk_level==='HIGH',med=risk.risk_level==='MEDIUM';
 return <div className="app-shell">
  <aside><div className="brand"><div className="brand-mark"><ShieldCheck/></div><div><b>RakshaCall</b><small>REAL-TIME SAFETY LAYER</small></div></div><nav><span className="active"><Activity/>Protection</span><span><ShieldCheck/>Risk intelligence</span><span><FileText/>Evidence vault</span><span><Users/>Trusted contacts</span></nav><div className="side-bottom"><div className="secure"><Lock/><div><b>Consent-first</b><small>No silent interception</small></div></div><button onClick={logout}>Sign out</button></div></aside>
  <main><header><div><p className="eyebrow">LIVE PROTECTION</p><h2>Security command center</h2></div><div className="header-right"><span className={`online ${aiStatus!=='connected'?'off':''}`}><i/> {aiStatus==='connected'?'GEMINI LIVE':'AI OFFLINE'}</span><button className="avatar">{(name||email||'R')[0].toUpperCase()}</button></div></header>
   <section className="hero"><div className="hero-copy"><div className="session-kicker"><Radio/> {session?`PROTECTED SESSION #${session.id}`:'READY TO PROTECT'}</div><h1>Stay calm.<br/><em>See the pressure clearly.</em></h1><p>RakshaCall analyzes permitted live conversation first, then adds supporting visual context. The system never silently intercepts encrypted calls.</p><div className="hero-buttons"><button className="primary" onClick={start}><Activity size={15}/> {session?'Protection active':'Start protection'}</button><button className={mic?'danger-btn':'ghost'} onClick={startMic}><Mic size={15}/> {mic?'Stop live audio':'Enable live audio'}</button><button className={camera?'active-btn':'ghost'} onClick={startCamera}><Video size={15}/> {camera?'Camera on':'Enable camera'}</button></div><div className="trust-row"><span><Lock/> Consent-first</span><span><Wifi/> Real-time AI</span><span><ShieldCheck/> Explainable</span></div></div><div className={`risk-orb ${high?'high':med?'medium':''}`}><div className="orb-core"/><div className="ring"/><small>CURRENT RISK</small><strong>{risk.risk_level}</strong><span>{Math.round((risk.fused_score||0)*100)} / 100</span></div></section>
   <section className="stats">{[['Protection sessions',stats.sessions||0],['Risk events',stats.events||0],['Trusted contacts',stats.contacts||0],['Evidence reports',stats.reports||0]].map(([a,b]:any)=><div className="stat" key={a}><Activity/><small>{a}</small><strong>{b}</strong><span>persisted data</span></div>)}</section>
   <section className="live-lab"><div className="section-head"><div><p className="eyebrow">REAL-TIME SIGNAL LAB</p><h3>Conversation is the primary signal.</h3></div><span className="model-chip"><Wifi/> {aiStatus==='connected'?'GEMINI LIVE CONNECTED':'CONNECTING / UNAVAILABLE'}</span></div><div className="lab-grid">
    <div className="panel transcript-panel"><div className="panel-head">LIVE TRANSCRIPT <span>{mic?'LISTENING':'STANDBY'}</span></div><div className="input-state"><div className={`mic-pulse ${mic?'on':''}`}><Mic/></div><div><b>{mic?'Streaming permitted audio':'Waiting for permission'}</b><small>{transcript||'Speak naturally. Detected content is analyzed in real time.'}</small></div></div><div className="transcript-box">{transcript||'No conversation captured yet.'}</div><div className="stage"><span>STAGE</span><b>{ai?.stage||risk.stage||'CONTACT'}</b><span>VELOCITY</span><b>{ai?.manipulation_velocity||'LOW'}</b></div></div>
    <div className="panel video-panel"><div className="panel-head">SUPPORTING VISION <span>{camera?'CONSENTED':'STANDBY'}</span></div><div className="video-box">{camera?<video ref={video} autoPlay muted playsInline/>:<><Video/><b>Camera is optional</b><small>Supporting signal only</small></>}</div><div className="signal-mini"><div><small>Visual AI</small><b>{Math.round((risk.visual_score||0)*100)}%</b><i style={{width:`${(risk.visual_score||0)*100}%`}}/></div><div><small>Liveness</small><b>{risk.liveness_score?Math.round(risk.liveness_score*100)+'%':'Not assessed'}</b><i style={{width:`${(risk.liveness_score||0)*100}%`}}/></div></div></div>
    <div className="panel fusion-panel"><div className="panel-head">EXPLAINABLE FUSION <span>PRIMARY CONVERSATION</span></div><div className="fusion-number">{risk.risk_level}<small>{Math.round((risk.fused_score||0)*100)} / 100</small></div><div className="meter"><i style={{width:`${(risk.fused_score||0)*100}%`}}/></div><div className="reasons">{(risk.reasons||[]).map((x:string)=><div key={x}><Check size={13}/>{x}</div>)}</div>{ai&&<div className="ai-note"><b>Gemini confidence {Math.round((ai.confidence||0)*100)}%</b><small>{(ai.tactics||[]).join(' · ')||'No tactic classified'}</small></div>}</div>
   </div></section>
   <section className="actions"><div className="action-card warning-card"><div className="action-icon"><PauseCircle/></div><small>01 · SAFETY BRAKE</small><h3>Pause before irreversible action.</h3><p>When high risk combines with payment, credential or remote-access pressure, interrupt the pressure loop.</p><button onClick={()=>setWarning(true)}>Open safety brake</button></div><div className="action-card"><div className="action-icon"><Users/></div><small>02 · TRUSTED CONTACT</small><h3>{contact?.name||'Add someone you trust.'}</h3><p>Consent-controlled alert. Real SMS delivery requires a configured provider.</p><button onClick={alertContact}><Phone/> Send alert</button></div><div className="action-card"><div className="action-icon"><FileText/></div><small>03 · EVIDENCE VAULT</small><h3>Preserve the timeline.</h3><p>Timestamped events with a SHA-256 chain for tamper evidence.</p><button onClick={makeEvidence}>Generate report <Download/></button></div></section>
   <section className="architecture"><div><p className="eyebrow">THE PROTECTION LOOP</p><h3>Detect → Warn → Verify → Connect → Preserve</h3><p>Local deterministic checks provide a guardrail. Gemini Live adds real-time contextual analysis. Visual input is optional and supporting.</p></div><div className="flow">{['Permitted audio','Speech / transcript','Scam intelligence','Risk fusion','Safety brake','Independent verify','Evidence'].map((x,i)=><div key={x}><span>0{i+1}</span>{x}</div>)}</div></section>
   <footer><span><ShieldCheck/> Risk indication, not legal determination.</span><span>Verify independently. Never transfer money under pressure.</span><a href="https://cybercrime.gov.in" target="_blank">Cybercrime portal <ExternalLink size={12}/></a></footer>
  </main>
  <canvas ref={canvas} style={{display:'none'}}/>
  <AnimatePresence>{warning&&<div className="overlay"><motion.div className="warning-modal" initial={{scale:.92,y:20}} animate={{scale:1,y:0}}><button className="close" onClick={()=>setWarning(false)}><X/></button><div className="warning-symbol"><AlertTriangle/></div><p className="eyebrow">RAKSHACALL SAFETY BRAKE</p><h2>Pause. Don't transfer anything.</h2><p>Elevated coercion or irreversible-action pressure was detected. Stop, disconnect if safe, and verify the caller using an official channel you find independently.</p><div className="warning-actions"><button className="primary" onClick={()=>{setWarning(false);alertContact()}}>Contact someone I trust <Users size={15}/></button><button className="ghost" onClick={()=>setWarning(false)}>I understand</button></div><small>India: cyber fraud helpline 1930 · cybercrime.gov.in</small></motion.div></div>}</AnimatePresence>
  {evidence&&<div className="overlay"><div className="modal"><button className="close" onClick={()=>setEvidence(null)}><X/></button><p className="eyebrow">EVIDENCE VAULT</p><h2>Integrity: {evidence.integrity}</h2><pre>{JSON.stringify(evidence,null,2)}</pre><button className="primary wide" onClick={()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(evidence,null,2)],{type:'application/json'}));a.download=`rakshacall-session-${session.id}.json`;a.click()}}><Download/> Export JSON</button></div></div>}
  {toast&&<div className="toast">{toast}</div>}
 </div>
}
function Auth({mode,setMode,email,setEmail,password,setPassword,name,setName,onSubmit}:{mode:'login'|'register',setMode:any,email:string,setEmail:any,password:string,setPassword:any,name:string,setName:any,onSubmit:any}){return <div className="auth-screen"><div className="auth-card"><div className="brand"><div className="brand-mark"><ShieldCheck/></div><div><b>RakshaCall</b><small>REAL-TIME SAFETY LAYER</small></div></div><p className="eyebrow">PRIVATE PROTECTION</p><h1>{mode==='login'?'Welcome back.':'Create your protection account.'}</h1><p>Your account stores protection events and evidence metadata. No demo data is pre-seeded.</p>{mode==='register'&&<input placeholder="Full name" value={name} onChange={e=>setName(e.target.value)}/>}<input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button className="primary wide" onClick={onSubmit}>{mode==='login'?'Sign in':'Create account'}</button><button className="link-btn" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Create a new account':'I already have an account'}</button><small className="auth-note"><Lock/> Real-time AI is optional until a Gemini API key is configured on the server.</small></div></div>}
createRoot(document.getElementById('root')!).render(<App/>);
